desc: "Xen-Troops development setup for Renesas RCAR Gen3 hardware"
min_ver: "0.4"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOM0_BUILD_DIR: "build-dom0"
  DOMD_BUILD_DIR: "build-domd"
  XT_DOMD_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-domd.dtb"
  XT_XEN_DTB_NAME: "%{SOC_FAMILY}-%{MACHINE}-xen.dtb"
  XT_PVR_NUM_OSID: "2"
  XT_OP_TEE_FLAVOUR: "generic_dt"
  XEN_URL: "git://git@gitpct.epam.com/rec-inv/xen.git;protocol=ssh;branch=v4.16rc_cr7"

common_data:
  # Sources used by all yocto-based domains
  sources: &COMMON_SOURCES
    - type: git
      url: "git://git.yoctoproject.org/poky"
      rev: dunfell
    - type: git
      url: "git://git.openembedded.org/meta-openembedded"
      rev: dunfell
    - type: git
      url: "git://git.yoctoproject.org/meta-virtualization"
      rev: dunfell
    - type: git
      url: "https://github.com/iusyk/meta-xt-common.git"
      rev: customize-xen-params
    - type: git
      url: "https://github.com/iusyk/meta-xt-rcar.git"
      rev: feature/move-dts

    # Common configuration options for all yocto-based domains
  conf: &COMMON_CONF
    - [SSTATE_DIR, "${TOPDIR}/../common_data/sstate"]
    - [DL_DIR, "${TOPDIR}/../common_data/downloads"]

    # Skip warning about missing "virtualization" distro feature
    - [SKIP_META_VIRT_SANITY_CHECK, "1"]

    # Use hypervisor console on all guests
    - [SERIAL_CONSOLES, "115200;hvc0"]

    # Configure number of supported GPU virtual guests
    - [XT_PVR_NUM_OSID, "%{XT_PVR_NUM_OSID}"]

    # Remove features that we are not using
    - [DISTRO_FEATURES_remove, "x11 gtk gobject-introspection-data wifi nfc bluetooth irda zeroconf 3g sysvinit"]

  # Conf options for domain that are built used renesas layer
  domd_domu_conf: &DOMD_DOMU_CONF
    - [MACHINE, "%{MACHINE}"]
    - [SOC_FAMILY, "%{SOC_FAMILY}"]

    # Add systemd configuration
    - [DISTRO_FEATURES_append, " systemd"]
    - [VIRTUAL-RUNTIME_init_manager, "systemd"]

    # add the static lib to SDK toolchain
    - [SDKIMAGE_FEATURES_append, " staticdev-pkgs"]

    # Enable Gfx Pkgs
    - [MACHINE_FEATURES_append, " gsx"]
    - [MULTI_PROVIDER_WHITELIST_append," virtual/libgl virtual/egl virtual/libgles1 virtual/libgles2"]

    # Add for gstreamer plugins ugly
    - [LICENSE_FLAGS_WHITELIST, "commercial"]

    # Add Capacity Aware migration Strategy (CAS)
    - [MACHINE_FEATURES_append, " cas"]

    # Remove ptest to reduce the build time
    - [DISTRO_FEATURES_remove, "ptest"]

    # HACK: force ipk instead of rpm b/c it makes troubles to PVR UM build otherwise
    - [PACKAGE_CLASSES, "package_ipk"]

  # The same set of layers and configs is used both in DomD and DomU
  # to build a DDK from source code
  ddk_source_overrides: &DDK_SOURCE_OVERRIDES
    sources:
      - type: git
        url: "git://git.openembedded.org/meta-python2"
        rev: dunfell
      - type: git
        url: "https://github.com/kraj/meta-clang"
        rev: dunfell
      - type: git
        url: "ssh://git@gitpct.epam.com/epmd-aepr/img-proprietary"
        rev: "ef1aa566d74a11c4d2ae9592474030a706b4cf39"
        dir: "proprietary"
    builder:
      conf:
        - [GLES_VERSION, "1.11"]
        - [PREFERRED_PROVIDER_gles-user-module,          "gles-user-module"]
        - [PREFERRED_VERSION_gles-user-module,           "${GLES_VERSION}"]
        - [PREFERRED_PROVIDER_kernel-module-gles,        "kernel-module-gles"]
        - [PREFERRED_VERSION_kernel-module-gles,         "${GLES_VERSION}"]
        - [PREFERRED_PROVIDER_gles-module-egl-headers,   "gles-module-egl-headers"]
        - [PREFERRED_VERSION_gles-module-egl-headers,    "${GLES_VERSION}"]
      layers:
        - "../meta-python2"
        - "../meta-clang"
        - "../meta-xt-rcar/meta-xt-rcar-proprietary"

components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      - *COMMON_SOURCES
      - type: git
        url: "https://github.com/iusyk/meta-xt-prod-cockpit-rcar.git"
        rev: devel-rcar
    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - [MACHINE, "generic-armv8-xt"]
        - [XT_DOMD_CONFIG_NAME, "%{XT_DOMD_CONFIG_NAME}"]
        - [XT_DOMD_DTB_NAME, "%{XT_DOMD_DTB_NAME}"]
        - [XT_DOM_NAME, "dom0"]
        - [XT_GUEST_INSTALL, "domd"]

        # Disable HWDB which quite huge (around 15MB) and is not required at all
        - [BAD_RECOMMENDATIONS_append, " udev-hwdb"]

        # Remove unused DISTRO_FEATURES
        - [DISTRO_FEATURES_remove, "acl alsa argp pcmcia usbgadget
                usbhost opengl ptest multiarch wayland vulkan
                sysvinit"]

        # Enable systemd on dom0
        - [DISTRO_FEATURES_append, " systemd"]
        - [VIRTUAL-RUNTIME_init_manager, "systemd"]

        # Do not install kernel image to rootfs to decrease initrd size
        - ["RDEPENDS_${KERNEL_PACKAGE_NAME}-base", ""]

        # get xen customized under cr7
        - [XEN_URL_pn-xen-tools, "%{XEN_URL}"]
        - [SRCREV_pn-xen-tools, "d9703fe08c3d32dbfb89ab10502ad2ffeb52de62"]
        - [XEN_URL_pn-xen, "%{XEN_URL}"]
        - [XEN_REL_pn-xen, "4.16"]
        - [XEN_REL_pn-xen-tools, "4.16"]
        - [SRCREV_pn-xen, "d9703fe08c3d32dbfb89ab10502ad2ffeb52de62"]

      layers:
        - "../meta-virtualization"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-dom0"
        - "../meta-xt-common/meta-xt-control-domain"
        - "../meta-xt-rcar/meta-xt-rcar-dom0"
        - "../meta-xt-prod-cockpit-rcar/meta-xt-prod-cockpit-rcar-control"
      build_target: core-image-thin-initramfs
      external_src:
        domd: "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/"
      additional_deps:
        - "%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
      target_images:
        - "tmp/deploy/images/generic-armv8-xt/Image"
        - "tmp/deploy/images/generic-armv8-xt/uInitramfs"

  domd:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
      - type: git
        url: git://git.yoctoproject.org/meta-selinux
        rev: dunfell
      - type: git
        url: "https://github.com/iusyk/meta-xt-prod-cockpit-rcar.git"
        rev: devel-rcar
      - type: git
        url: "https://github.com/meta-qt5/meta-qt5"
        rev: "45c45a1524bd6a8dbd3dcf2077c791a23fec8d91"
      - type: git
        url: "https://github.com/xen-troops/meta-renesas.git"
        rev: "Renesas-Yocto-v5.1-patched"
    builder:
      type: yocto
      work_dir: "%{DOMD_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - *DOMD_DOMU_CONF
        - [XT_DOM_NAME, "domd"]
        - [XT_OP_TEE_FLAVOUR, "%{XT_OP_TEE_FLAVOUR}"]
        - [XT_DEVICE_TREES, "%{XT_DOMD_DTB_NAME} %{XT_XEN_DTB_NAME"]
        # Machine feature 'multimedia' is used to enable (VSP in domd) and (LOSSY build option in ATF)
        - [MACHINE_FEATURES_append, " multimedia"]

        # take dedicated cr7 kernel
        - [RENESAS_BSP_URL_pn-linux-renesas,  "git://git@gitpct.epam.com/rec-inv/linux.git;protocol=ssh"]
        - [BRANCH_pn-linux-renesas, "v5.10_cr7_aosbox"]

        # get xen customized under cr7
        - [XEN_URL_pn-xen-tools, "%{XEN_URL}"]
        - [SRCREV_pn-xen-tools, "d9703fe08c3d32dbfb89ab10502ad2ffeb52de62"]
        - [XEN_URL_pn-xen, "%{XEN_URL}"]
        - [XEN_REL_pn-xen, "4.16"]
        - [XEN_REL_pn-xen-tools, "4.16"]
        - [SRCREV_pn-xen, "d9703fe08c3d32dbfb89ab10502ad2ffeb52de62"]
        
        # add graphic packages required qt
        - [DISTRO_FEATURES_append, " pam"]
        - [PREFERRED_PROVIDER_virtual/egl, "libegl"]
        - [PREFERRED_PROVIDER_virtual/libgl, ""]
        - [PREFERRED_PROVIDER_virtual/mesa, ""]
        - [PREFERRED_PROVIDER_virtual/libgbm, "libgbm"]
        - [PREFERRED_PROVIDER_libgbm-dev, "libgbm"]
        - [BBMASK_append, "mesa-gl"]

      build_target: core-image-minimal
      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-renesas/meta-rcar-gen3"
        - "../meta-virtualization"
        - "../meta-selinux"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-networking"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-driver-domain"
        - "../meta-xt-rcar/meta-xt-rcar-fixups"
        - "../meta-xt-rcar/meta-xt-rcar-driver-domain"
        - "../meta-xt-prod-cockpit-rcar/meta-xt-prod-cockpit-rcar-driver-domain"
        - "../meta-qt5"
        - "../meta-xt-prod-cockpit-rcar/meta-xt-prod-cockpit-rcar-qt5"          
      target_images:
        - "tmp/deploy/images/%{MACHINE}/Image"
        - "tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
        - "tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
        - "tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"
        - "tmp/deploy/images/%{MACHINE}/core-image-minimal-%{MACHINE}.ext4"

images:
  full:
    type: gpt
    desc: "Full SD-card/eMMC image"
    partitions:
      boot:
        gpt_type: 21686148-6449-6E6F-744E-656564454649 # BIOS boot partition (kinda...)
        type: ext4
        size: 128 MiB
        files:
          "Image": "%{YOCTOS_WORK_DIR}/build-dom0/tmp/deploy/images/generic-armv8-xt/Image"
          "uInitramfs": "%{YOCTOS_WORK_DIR}/build-dom0/tmp/deploy/images/generic-armv8-xt/uInitramfs"
          "xen": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/xen-%{MACHINE}.uImage"
          "xenpolicy": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/xenpolicy-%{MACHINE}"
          "xen.dtb": "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/%{XT_XEN_DTB_NAME}"
      domd_rootfs:
        gpt_type: B921B045-1DF0-41C3-AF44-4C6F280D3FAE # Linux aarch64 root
        type: raw_image
        image_path: "%{YOCTOS_WORK_DIR}/build-domd/tmp/deploy/images/%{MACHINE}/core-image-minimal-%{MACHINE}.ext4"

parameters:
  # Machines
  MACHINE:
    desc: "RCAR Gen3-based device"
    h3ulcb-4x2g-kf:
      default: true
      overrides:
        variables:
          MACHINE: "h3ulcb"
          SOC_FAMILY: "r8a7795"
          XT_DOMD_CONFIG_NAME: "domd-h3ulcb-4x2g-kf.cfg"
          XT_OP_TEE_FLAVOUR: "salvator_h3_4x2g"
          XT_DOMD_DTB_NAME: "r8a77951-h3ulcb-4x2g-kf-domd.dtb"
          XT_XEN_DTB_NAME: "r8a77951-h3ulcb-4x2g-kf-xen.dtb"
        components:
          domd:
            sources:
              - type: git
                url: "https://github.com/CogentEmbedded/meta-rcar.git"
                rev: v5.1.0
            builder:
              layers:
                - "../meta-rcar/meta-rcar-gen3-adas"
                - "../meta-xt-rcar/meta-xt-cogent-fixups"
              conf:
                # Ignore OP-TEE patches as we have own OP-TEE
                -  [BBMASK_append, "|meta-rcar-gen3-adas/recipes-bsp/optee"]
  PREBUILT_DDK:
    desc: "Use pre-built GPU drivers"
    "no":
      default: true
      overrides:
        components:
          domd:
            *DDK_SOURCE_OVERRIDES

  ENABLE_MM:
    desc: "Enable Multimedia support"
    "no":
      default: true
      overrides:
        components:
          domd:
            builder:
              conf:
                # Mask MMP recipes
                - [BBMASK_append, "|kernel-module-uvcs-drv|omx-user-module"]          
